language: python
os:
  - windows
  - linux
python:
  - "3.6"
install:
  - python setup.py install
before_script:
  - python -m CostumePy.server &
script:
  - python -m unittest discover -s tests -v
  - python -m unittest discover -s tests -v