language: python

matrix:
  include:

    - os: windows
      language: sh
      python: "3.8"
      before_install:
      - choco install python3
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      - python -m ensurepip --upgrade

    - os: linux
      python: "3.6"


jobs:
  include:
  - stage: Server_Connection_Test
    script: python -m unittest tests/test_server_connection.py

  - stage: Main_Test_Suite
    script: python -m unittest discover -s tests -v

  - stage: Duplicate_Test_Suite
    script: python -m unittest discover -s tests -v


install:
  - python setup.py install
before_script:
  - python -m CostumePy.server &